spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://roulette-app-database-1.cd0y24wkquzb.ap-northeast-2.rds.amazonaws.com:3306/roulette?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: song1074++

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.spring.board
  configuration:
    map-underscore-to-camel-case: true


