name: Backend Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradle
        run: chmod +x backend/gradlew

      - name: Build backend
        run: |
          cd backend
          ./gradlew clean build -x test

      - name: Restart backend
        run: |
          pkill -f 'java -jar' || true
          JAR_FILE=$(ls backend/build/libs/*.jar | grep -v 'plain.jar' | head -n 1)
          cp "$JAR_FILE" /opt/ustra-roulette-app/ustra-roulette-app-0.0.1-SNAPSHOT.jar
          sudo systemctl restart roulette