name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Grant execute permission for Gradle
        run: chmod +x backend/gradlew

      - name: Build with Gradle
        run: cd backend && ./gradlew build -x test

      - name: Copy JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no backend/build/libs/ustra-roulette-app-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/roulette-app.jar

      - name: Restart app via systemctl
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} 'sudo systemctl restart ustra-roulette-app'
