name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Spring Boot
        run: cd backend && ./gradlew build -x test

      - name: Restart Spring Boot
        run: |
          sudo mv backend/build/libs/ustra-roulette-app-0.0.1-SNAPSHOT.jar /opt/ustra-roulette-app/ustra-roulette-app-0.0.1-SNAPSHOT.jar
          sudo systemctl restart ustra-roulette-app
          sudo systemctl status ustra-roulette-app --no-pager
