name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Connect & Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo ">>> 기존 앱 삭제"
            rm -rf ~/roulette-app

            echo ">>> git clone"
            git clone https://github.com/ckehf223/roulette-app.git

            echo ">>> backend 디렉토리 이동"
            cd ~/roulette-app/backend

            echo ">>> 실행 중인 앱 종료"
            pkill -f 'ustra-roulette-app' || true

            echo ">>> gradle 빌드"
            chmod +x ./gradlew
            ./gradlew build

            echo ">>> 앱 실행"
            nohup java -jar build/libs/ustra-roulette-app-0.0.1-SNAPSHOT.jar > ~/app.log 2>&1 &
